server:
  port: 8085

spring:
  application:
    name: leyou-user
  datasource:
    url: jdbc:mysql:///hm49
    data-username: root
    data-password: 123123
  redis:
    host: 192.168.1.106
  rabbitmq:
    host: 192.168.1.106
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5

mybatis:
  type-aliases-package: com.leyou.user.pojo